ALTER TABLE `Cliente`
  MODIFY COLUMN `telefono` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `empresa` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `nif` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `direccion` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `direccionComplementaria` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `codigoPostal` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `ciudad` VARCHAR(191) NULL DEFAULT NULL,
  MODIFY COLUMN `provincia` VARCHAR(191) NULL DEFAULT NULL;
